# Generated by Django 2.1.2 on 2018-10-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optioncontract',
            name='k_expiration_date',
            field=models.DateField(verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='optioncontract',
            name='k_open_date',
            field=models.DateField(verbose_name='Date Opened'),
        ),
    ]
