# Generated by Django 2.1.2 on 2018-10-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trades', '0002_auto_20181016_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directional_bias', models.CharField(choices=[('Bullish', 'Bullish'), ('Bearish', 'Bearish'), ('Neutral', 'Neutral')], default='Bullish', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='optioncontract',
            name='directional_bias',
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='option_type',
            field=models.CharField(choices=[('Buy Call', 'Buy Call'), ('Buy Put', 'Buy Put'), ('Sell Call', 'Sell Call'), ('Sell Put', 'Sell Put')], default='Buy Call', max_length=10),
        ),
    ]
