# Generated by Django 2.1.2 on 2018-10-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trades', '0003_auto_20181018_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='optioncontract',
            name='option_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optioncontract',
            name='strike_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
            preserve_default=False,
        ),
    ]
